---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# nAMD_va_predictor

<!-- badges: start -->
<!-- badges: end -->

An R Shiny app that describes visual outcomes at 1 year for a given baseline visual acuity, based on publicly available real-world data included in the [eyedata](https://github.com/tjebo/eyedata) package. Visit https://7hocgq-rmgpanw.shinyapps.io/nAMD_va_predictor/ to try out app.

Summary of dataset:

```{r}
library(eyedata)
suppressPackageStartupMessages(library(tidyverse))
amd %>% 
  mutate(patID = as.integer(str_remove(string = patID,
                                       pattern = "id_"))) %>% 
  group_by(patID) %>% 
  arrange(time) %>% 
  summarise(sex = sex[1],
            age = age[1],
            ethnicity = ethnicity[1],
            follow_up_length = max(time, na.rm = TRUE),
            baseline_va = va[1],
            regimen = str_c(unique(regimen, 
                                   sep = "", 
                                   collapse = "; "))) %>% 
  select(-patID) %>% 
  gtsummary::tbl_summary() %>% 
  gtsummary::as_tibble() %>% 
  mutate(across(everything(),
                ~ ifelse(is.na(.x), "", .x))) %>% 
  knitr::kable()
```

